src/apps/productos/urls.py
from django.urls import path
from . import views
from apps.comentarios import views as views_c

app_name = "productos"

urladmin = [
    path("Admin/Listar/", views.ListarAdmin.as_view(), name="admin_listar"),
    path("Admin/Nuevo/", views.Crear.as_view(), name="admin_nuevo"),
    path("Admin/Editar/<int:pk>/", views.Editar.as_view(), name="admin_editar"),
    path("Admin/Borrar/<int:pk>/", views.borrar, name="admin_borrar"),
    path("Admin/Detalle/<int:pk>/", views.Detalle.as_view(), name="admin_detalle"),

]

urlsite = [
    #path("ListarProductos/", views.listar, name="listar"),
    path("Listar/", views.Listar.as_view(), name="listar"),
    path("Favoritos", views.ListarFavoritos.as_view(), name="listar_favoritos"),
    path("<int:pk>/", views.producto_detalle, name="detalle"),
    path("AgregarFavorito/<int:id>/", views.manejar_favorito, name="manejar_favorito"),
    #path("<int:id>/comentar", views_c.agregar, name="agregar_comentario")
]

urlpatterns = urladmin + urlsite

src/hugoOfemme/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    #Includes
    path("Productos/", include("apps.productos.urls")),
    path("Usuario/", include("apps.usuarios.urls")),
    path("", include("apps.ordenes.urls")),

    #Urls propias del proyecto
    #path("", views.inicio, name="inicio"),
    path("", views.Inicio.as_view(), name = "inicio"),
    path("login/", auth_views.LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", auth_views.logout_then_login, name="logout"),
    path("checkout/", views.checkout, name="checkout"),
    path("Carrito/", views.carrito, name="carrito"),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

src/templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- CSS only -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-beta.2/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/favoritos.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Barlow&display=swap');
    </style>
    <title>Inicio</title>
    <script type="text/javascript">
        var user = '{{request.user}}';
        function getToken(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getToken('csrftoken');
    </script>
</head>
<body>
    {% include "base/nav.html" %}
    {% block header %}
    
    {% endblock header %}
    
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            {% block contenido %}
        
            {% endblock contenido %}
        </div>
    </section>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/249d0087ac.js" crossorigin="anonymous"></script>
    <!-- <script type="text/javascript" src="{% static 'js/carrito.js' %}"></script> -->
</body>
</html>

src/templates/base/header.html
<nav class="navbar navbar-expand navbar-light bg-light flex-column flex-md-row pipe-navbar justify-md-content-between">
    <a class="navbar-brand" href="{% url 'inicio' %}"><img src="https://pipe.bot/img/logo.svg" width="30" height="30" class="d-inline-block align-top" /> CarriSneakers</a>
    <div class="navbar-nav-scroll ml-md-auto">
        <ul class="navbar-nav pipe-navbar-nav">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link prueba" href="" rel="noopener">{{user}}</a>
                </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'productos:listar' %}" rel="noopener">Catalogo</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#" target="_blank" rel="noopener">-</a>
            </li>       
            <li class="nav-item">
                <a class="nav-link" href="#">-</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">-</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="#">-</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#" target="_blank" rel="noopener">-</a>
            </li>   
        </ul>
    </div>
    <div>
        <ul class="navbar-nav pipe-navbar-nav">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link prueba" href="{% url 'logout' %}" rel="noopener">Cerrar Sesion</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link prueba" href="{% url 'login' %}" rel="noopener">Iniciar Sesion</a>
                </li>
            {% endif %}
            
            
        </ul>
    </div>
</nav> 

src/templates/base/nav.html
<nav class="navbar navbar-expand navbar-light bg-light flex-column flex-md-row pipe-navbar justify-md-content-between">
    <a class="navbar-brand" href="{% url 'inicio' %}"><img src="https://pipe.bot/img/logo.svg" width="30" height="30" class="d-inline-block align-top" /></a>
    <div class="navbar-nav-scroll ml-md-auto">
        <ul class="navbar-nav pipe-navbar-nav">
            {% if user.is_authenticated %}
                {% if user.is_superuser %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'productos:admin_listar' %}" rel="noopener">Panel</a>
                    </li>
                {% endif %}
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'productos:listar' %}" rel="noopener">Catalogo</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'productos:listar_favoritos' %}" rel="noopener">Mis favoritos</a>
            </li> 
            <li class="nav-item">
                <a class="nav-link" href="{% url 'carrito' %}"><i class="fa-solid fa-cart-shopping fa-lg"></i></a>
            </li>    
        </ul>
    </div>
    <div>
        <ul class="navbar-nav pipe-navbar-nav">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link prueba" href="{% url 'logout' %}" rel="noopener">Cerrar Sesion</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link prueba" href="{% url 'login' %}" rel="noopener">Iniciar Sesion</a>
                </li>
            {% endif %}
            
            
        </ul>
    </div>
</nav> 