src/apps/productos/urls.py
from django.urls import path
from . import views
from apps.comentarios import views as views_c

app_name = "productos"

urladmin = [
    path("Admin/Listar/", views.ListarAdmin.as_view(), name="admin_listar"),
    path("Admin/Nuevo/", views.Crear.as_view(), name="admin_nuevo"),
    path("Admin/Editar/<int:pk>/", views.Editar.as_view(), name="admin_editar"),
    path("Admin/Borrar/<int:pk>/", views.borrar, name="admin_borrar"),
    path("Admin/Detalle/<int:pk>/", views.Detalle.as_view(), name="admin_detalle"),

]

urlsite = [
    #path("ListarProductos/", views.listar, name="listar"),
    path("Listar/", views.Listar.as_view(), name="listar"),
    path("Favoritos", views.ListarFavoritos.as_view(), name="listar_favoritos"),
    path("<int:pk>/", views.producto_detalle, name="detalle"),
    path("AgregarFavorito/<int:id>/", views.manejar_favorito, name="manejar_favorito"),
    #path("<int:id>/comentar", views_c.agregar, name="agregar_comentario")
]

urlpatterns = urladmin + urlsite

src/hugoOfemme/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    #Includes
    path("Productos/", include("apps.productos.urls")),
    path("Usuario/", include("apps.usuarios.urls")),
    path("", include("apps.ordenes.urls")),

    #Urls propias del proyecto
    #path("", views.inicio, name="inicio"),
    path("", views.Inicio.as_view(), name = "inicio"),
    path("login/", auth_views.LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", auth_views.logout_then_login, name="logout"),
    path("checkout/", views.checkout, name="checkout"),
    path("Carrito/", views.carrito, name="carrito"),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

src/apps/productos/models.py
from pyexpat import model
from django.db import models
from django.urls import reverse
from apps.usuarios.models import Usuario

class Marca(models.Model):
    nombre = models.CharField(max_length=250)

    class Meta:
        db_table = "marcas"
    
    def __str__(self):
        return self.nombre


class Tag(models.Model):
    nombre = models.CharField(max_length=250)

    class Meta:
        db_table = "tags"

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre = models.CharField(max_length=250)
    precio = models.DecimalField(max_digits=9, decimal_places=2)
    cantidad = models.IntegerField(default=0)
    activo = models.BooleanField(default=True)
    imagen = models.ImageField(upload_to = "productos", null=True, blank=True)
    marca = models.ForeignKey(Marca, on_delete=models.CASCADE, related_name="productos_relacionados", null=True)
    tags = models.ManyToManyField(Tag)
    favorito = models.ManyToManyField(Usuario , related_name="favorito", blank=True)

    class Meta:
        db_table = "productos"
        
    def __str__(self):
        return self.nombre



class ProductoTag(models.Model):
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)

src/apps/productos/forms.py
from pyexpat import model
from django import forms
from .models import Producto

class ProductoForm(forms.ModelForm):
    nombre = forms.CharField(label="Nombre", required=True, widget=forms.TextInput(attrs={"class": "form-control"}))
    imagen = forms.ImageField(label="Imagen", required=False)
    class Meta:
        model = Producto
        fields = ["nombre", "activo", "precio", "cantidad", "imagen"]

src/apps/productos/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView
from django.views.generic.edit import UpdateView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.core.paginator import Paginator

from apps.core.decorators import superuser_required
from apps.core.mixins import SuperUserRequiredMixin
from apps.comentarios.forms import ComentarioForm
from apps.comentarios.models import Comentario

from .models import Producto
from .forms import ProductoForm


# Create your views here.


"""
def listar(request):
    template_name = "productos/listar.html"
    ctx = {
        "lista_productos": Producto.objects.all()
    }
    return render(request, template_name, ctx)
"""

class Listar(ListView):
    template_name = "productos/listar.html"
    paginate_by = 10
    model = Producto
    context_object_name = "lista_productos"

    def get_context_data(self, **kwargs):
        context = super(Listar, self).get_context_data(**kwargs) 
        context["nombre_producto"] = self.request.GET.get("nombre_producto", "")
        productos = Producto.objects.filter(activo=True)
        
        if self.request.user.is_authenticated:
            favoritos = []
            for p in productos:
                if p.favorito.filter(id=self.request.user.id).exists():
                    favoritos.append(p)
            context["fav_productos"] = favoritos
        return context
        
    def get_queryset(self):
        query = Producto.objects.filter(activo=True)
        nombre_producto = self.request.GET.get("nombre_producto", None)
        if nombre_producto:
            query = query.filter(nombre__icontains=nombre_producto) 
        return query

class ListarFavoritos(ListView, LoginRequiredMixin):
    template_name = "productos/favoritos.html"
    model = Producto
    
    def get_context_data(self, **kwargs):
        context = super(ListarFavoritos, self).get_context_data(**kwargs) 
        productos = Producto.objects.filter(activo=True)
        favoritos = []
        for p in productos:
            if p.favorito.filter(id=self.request.user.id).exists():
                favoritos.append(p)
        context["fav_productos"] = favoritos
        return context


def producto_detalle(request, pk):
    p = get_object_or_404(Producto, id=pk)
    form = ComentarioForm()
    comentarios = Comentario.objects.all().filter(producto=p.id).order_by('-id')
    cant_comentarios = comentarios.count()
    favorito = False
    if request.user.is_authenticated:
        if p.favorito.filter(id=request.user.id).exists():
            favorito = True

        if request.method == "POST":
            form = ComentarioForm(request.POST)
            if form.is_valid():
                form.instance.usuario = request.user
                form.instance.producto = p
                form.save()
                return redirect("productos:detalle", pk)
   
    ctx = {
        "producto": p,
        "form": form,
        "es_favorito": favorito,
        "comentarios": comentarios,
        "cant_comentarios": cant_comentarios
    }

    return render(request, "productos/detalle.html", ctx)

@superuser_required()
def manejar_favorito(request, id):
    p = get_object_or_404(Producto, id=id)
    if p.favorito.filter(id=request.user.id).exists():
        p.favorito.remove(request.user)
    else:
        p.favorito.add(request.user)

    return HttpResponseRedirect(request.META["HTTP_REFERER"])



# --------------------------------------------------------
#               VISTAS PARA EL ADMIN
# --------------------------------------------------------


class ListarAdmin(SuperUserRequiredMixin,LoginRequiredMixin, ListView):
    template_name = "productos/admin/listar.html"
    model = Producto
    context_object_name = "lista_productos"

    
    

class Crear(SuperUserRequiredMixin, LoginRequiredMixin, CreateView):
    template_name = "productos/admin/nuevo.html"
    model = Producto
    form_class = ProductoForm

    def get_success_url(self, **kwargs):
        return reverse_lazy("productos:admin_listar")

class Editar(SuperUserRequiredMixin, LoginRequiredMixin, UpdateView):
    template_name = "productos/admin/editar.html"
    model = Producto
    form_class = ProductoForm

    def get_success_url(self, **kwargs):
        return reverse_lazy("productos:admin_listar")

class Detalle(SuperUserRequiredMixin, LoginRequiredMixin, DetailView):
    model = Producto
    template_name = "productos/admin/detalle.html"


@superuser_required()
def borrar(request, pk):
    p = Producto.objects.get(id=pk)
    p.delete()
    return redirect("productos:admin_listar")

src/templates/productos/admin/detalle.html
{% extends 'base/admin/base.html' %}

{% block contenido %}
    <h1>{{object.nombre}}</h1>
    <div class="row">
        <div class="col-md-6">
            {% if object.imagen %}
                <img src="{{object.imagen.url}}" alt="imagen">
            {% else %}
                <p>Imagen no disponible</p>
            {% endif %}
        </div>
        <div class="col-md-6">
            <h1>$ {{object.precio}}</h1>
            <small>Total de unidades: <b>{{object.cantidad}}</b></small>
            <hr>
            {% if object.activo %}
                <small>El producto se encuentra activo</small>
            {% else %}
                <small>El producto no se encuentra activo</small>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col">
            <a href="{% url 'productos:admin_listar' %}">Volver</a>
        </div>
    </div>
{% endblock contenido %}

src/templates/productos/admin/editar.html
{% extends 'base/admin/base.html' %}

{% block contenido %}
    # enctype para trabajar con imagenes en el formulario
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            {% include 'includes/form_errors.html' %}
        </div>
        {{form.as_p}}
        <a href="{% url 'productos:admin_listar' %}">Cancelar</a>
        <button class="btn btn-primary" type="submit">Guardar</button>
        <a href="{% url 'productos:admin_borrar' object.id %}">Borrar</a>
    </form>

{% endblock contenido%}

src/templates/productos/admin/listar.html
{% extends 'base/admin/base.html' %}

{% block contenido %}
    <a href="{% url 'productos:admin_nuevo' %}">Nuevo producto</a>
    <table class="table">
        <thead>
            <th scope="col">Codigo</th>
            <th scope="col">Nombre</th>
            <th scope="col">Precio</th>
            <th scope="col">Cantidad</th>
            <th scope="col">Activo</th>
            <th></th>
        </thead>
        <tbody>
            {% for producto in lista_productos %}
                <tr>
                    <th scope="row">{{producto.id}}</th>
                    <td>{{producto.nombre}}</td>
                    <td>{{producto.precio}}</td>
                    <td>{{producto.cantidad}}</td>
                    <td>{{producto.activo}}</td>
                    <td>
                        <a href="{% url 'productos:admin_editar' producto.id %}">Editar</a>
                        <a href="{% url 'productos:admin_borrar' producto.id %}">Borrar</a>
                        <a href="{% url 'productos:admin_detalle' producto.id %}">Visualizar</a>
                    </td>
                </tr>        
            {% endfor %}
        </tbody>
    </table>

    
{% endblock contenido %}

src/templates/productos/admin/nuevo.html
{% extends 'base/admin/base.html' %}

{% block contenido %}
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <a href="{% url 'productos:admin_listar' %}">Cancelar</a>
        <button class="btn btn-primary" type="submit">Guardar</button>
    </form>

{% endblock contenido%}