src/apps/ordenes/urls.py
from django.urls import path
from . import views

app_name = "orden"


urlpatterns = [
    #path("ListarProductos/", views.listar, name="listar"),
    #path("update_item/", views.updateItem, name="update_item"),
    path("update_item/<str:type>/<int:pk>", views.updateItem, name="update_item"),
]

src/apps/productos/urls.py
from django.urls import path
from . import views
from apps.comentarios import views as views_c

app_name = "productos"

urladmin = [
    path("Admin/Listar/", views.ListarAdmin.as_view(), name="admin_listar"),
    path("Admin/Nuevo/", views.Crear.as_view(), name="admin_nuevo"),
    path("Admin/Editar/<int:pk>/", views.Editar.as_view(), name="admin_editar"),
    path("Admin/Borrar/<int:pk>/", views.borrar, name="admin_borrar"),
    path("Admin/Detalle/<int:pk>/", views.Detalle.as_view(), name="admin_detalle"),

]

urlsite = [
    #path("ListarProductos/", views.listar, name="listar"),
    path("Listar/", views.Listar.as_view(), name="listar"),
    path("Favoritos", views.ListarFavoritos.as_view(), name="listar_favoritos"),
    path("<int:pk>/", views.producto_detalle, name="detalle"),
    path("AgregarFavorito/<int:id>/", views.manejar_favorito, name="manejar_favorito"),
    #path("<int:id>/comentar", views_c.agregar, name="agregar_comentario")
]

urlpatterns = urladmin + urlsite

src/hugoOfemme/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    #Includes
    path("Productos/", include("apps.productos.urls")),
    path("Usuario/", include("apps.usuarios.urls")),
    path("", include("apps.ordenes.urls")),

    #Urls propias del proyecto
    #path("", views.inicio, name="inicio"),
    path("", views.Inicio.as_view(), name = "inicio"),
    path("login/", auth_views.LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", auth_views.logout_then_login, name="logout"),
    path("checkout/", views.checkout, name="checkout"),
    path("Carrito/", views.carrito, name="carrito"),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

src/apps/productos/models.py
from pyexpat import model
from django.db import models
from django.urls import reverse
from apps.usuarios.models import Usuario

class Marca(models.Model):
    nombre = models.CharField(max_length=250)

    class Meta:
        db_table = "marcas"
    
    def __str__(self):
        return self.nombre


class Tag(models.Model):
    nombre = models.CharField(max_length=250)

    class Meta:
        db_table = "tags"

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre = models.CharField(max_length=250)
    precio = models.DecimalField(max_digits=9, decimal_places=2)
    cantidad = models.IntegerField(default=0)
    activo = models.BooleanField(default=True)
    imagen = models.ImageField(upload_to = "productos", null=True, blank=True)
    marca = models.ForeignKey(Marca, on_delete=models.CASCADE, related_name="productos_relacionados", null=True)
    tags = models.ManyToManyField(Tag)
    favorito = models.ManyToManyField(Usuario , related_name="favorito", blank=True)

    class Meta:
        db_table = "productos"
        
    def __str__(self):
        return self.nombre



class ProductoTag(models.Model):
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)

src/apps/productos/forms.py
from pyexpat import model
from django import forms
from .models import Producto

class ProductoForm(forms.ModelForm):
    nombre = forms.CharField(label="Nombre", required=True, widget=forms.TextInput(attrs={"class": "form-control"}))
    imagen = forms.ImageField(label="Imagen", required=False)
    class Meta:
        model = Producto
        fields = ["nombre", "activo", "precio", "cantidad", "imagen"]

src/apps/productos/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView
from django.views.generic.edit import UpdateView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.core.paginator import Paginator

from apps.core.decorators import superuser_required
from apps.core.mixins import SuperUserRequiredMixin
from apps.comentarios.forms import ComentarioForm
from apps.comentarios.models import Comentario

from .models import Producto
from .forms import ProductoForm


# Create your views here.


"""
def listar(request):
    template_name = "productos/listar.html"
    ctx = {
        "lista_productos": Producto.objects.all()
    }
    return render(request, template_name, ctx)
"""

class Listar(ListView):
    template_name = "productos/listar.html"
    paginate_by = 10
    model = Producto
    context_object_name = "lista_productos"

    def get_context_data(self, **kwargs):
        context = super(Listar, self).get_context_data(**kwargs) 
        context["nombre_producto"] = self.request.GET.get("nombre_producto", "")
        productos = Producto.objects.filter(activo=True)
        
        if self.request.user.is_authenticated:
            favoritos = []
            for p in productos:
                if p.favorito.filter(id=self.request.user.id).exists():
                    favoritos.append(p)
            context["fav_productos"] = favoritos
        return context
        
    def get_queryset(self):
        query = Producto.objects.filter(activo=True)
        nombre_producto = self.request.GET.get("nombre_producto", None)
        if nombre_producto:
            query = query.filter(nombre__icontains=nombre_producto) 
        return query

class ListarFavoritos(ListView, LoginRequiredMixin):
    template_name = "productos/favoritos.html"
    model = Producto
    
    def get_context_data(self, **kwargs):
        context = super(ListarFavoritos, self).get_context_data(**kwargs) 
        productos = Producto.objects.filter(activo=True)
        favoritos = []
        for p in productos:
            if p.favorito.filter(id=self.request.user.id).exists():
                favoritos.append(p)
        context["fav_productos"] = favoritos
        return context


def producto_detalle(request, pk):
    p = get_object_or_404(Producto, id=pk)
    form = ComentarioForm()
    comentarios = Comentario.objects.all().filter(producto=p.id).order_by('-id')
    cant_comentarios = comentarios.count()
    favorito = False
    if request.user.is_authenticated:
        if p.favorito.filter(id=request.user.id).exists():
            favorito = True

        if request.method == "POST":
            form = ComentarioForm(request.POST)
            if form.is_valid():
                form.instance.usuario = request.user
                form.instance.producto = p
                form.save()
                return redirect("productos:detalle", pk)
   
    ctx = {
        "producto": p,
        "form": form,
        "es_favorito": favorito,
        "comentarios": comentarios,
        "cant_comentarios": cant_comentarios
    }

    return render(request, "productos/detalle.html", ctx)

@superuser_required()
def manejar_favorito(request, id):
    p = get_object_or_404(Producto, id=id)
    if p.favorito.filter(id=request.user.id).exists():
        p.favorito.remove(request.user)
    else:
        p.favorito.add(request.user)

    return HttpResponseRedirect(request.META["HTTP_REFERER"])



# --------------------------------------------------------
#               VISTAS PARA EL ADMIN
# --------------------------------------------------------


class ListarAdmin(SuperUserRequiredMixin,LoginRequiredMixin, ListView):
    template_name = "productos/admin/listar.html"
    model = Producto
    context_object_name = "lista_productos"

    
    

class Crear(SuperUserRequiredMixin, LoginRequiredMixin, CreateView):
    template_name = "productos/admin/nuevo.html"
    model = Producto
    form_class = ProductoForm

    def get_success_url(self, **kwargs):
        return reverse_lazy("productos:admin_listar")

class Editar(SuperUserRequiredMixin, LoginRequiredMixin, UpdateView):
    template_name = "productos/admin/editar.html"
    model = Producto
    form_class = ProductoForm

    def get_success_url(self, **kwargs):
        return reverse_lazy("productos:admin_listar")

class Detalle(SuperUserRequiredMixin, LoginRequiredMixin, DetailView):
    model = Producto
    template_name = "productos/admin/detalle.html"


@superuser_required()
def borrar(request, pk):
    p = Producto.objects.get(id=pk)
    p.delete()
    return redirect("productos:admin_listar")

src/templates/productos/includes/card_favorito.html
<div class="card mb-3" style="max-width: 540px;">
    <div class="row g-0">
        <div class="col-md-4">
            {% if p.imagen %}
                <img class="img-fluid rounded-start" src="{{p.imagen.url}}" alt="Card image cap" height="250px">
            {% else %}
                <img class="img-fluid rounded-start" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="...">
            {% endif %}
        </div>
        <div class="col-md-8">
            <div class="card-body">               
                <div class="card-head">
                    <h5 class="card-title">{{p.marca.nombre}} {{p.nombre}}</h5>
                    <a class="fav-card-icon" href="{% url 'productos:manejar_favorito' id=p.id %}">
                        <i class="fa-solid fa-trash-can fa-lg"></i>  
                    </a>
                </div>
                <p class="card-text">Descripcion</p>
                <p class="card-text"><small class="text-muted"> ${{p.precio}}</small></p>
            </div>
            <div class="add-to-cart-text-button-container">
                <a class="visit-product-detail" href="{% url 'productos:detalle' pk=p.id%}">
                    <button type="button" class="btn btn-dark">Ver detalle</button>
                </a>
            </div>
        </div>
    </div>
</div>

src/templates/productos/includes/card_producto.html
<div class="card h-100">
    <!-- Sale badge-->
    {% if user.is_authenticated %}
        <div class="position-absolute" style="top: 0.5rem; right: 0.5rem" id="favourite-section">
            <a href="{% url 'productos:manejar_favorito' id=p.id %}">
                {% if p in fav_productos %}
                    <i class="fa-solid fa-heart fa-lg"></i>  
                {% else %}
                    <i class="fa-regular fa-heart fa-lg"></i>
                {% endif %} 
            </a>
            
        </div>
    {% endif %}
    
    <!-- Product image-->
    {% if p.imagen %}
        <img class="card-img-top" src="{{p.imagen.url}}" alt="Card image cap" height="250px">
    {% else %}
        <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="...">
    {% endif %}
    <!-- Product details-->
    <div class="card-body p-4">
        <a href="{% url 'productos:detalle' pk=p.id%}" style="text-decoration:none; color: inherit">
            <div class="text-center">
                <!-- Product name-->
                <h5 class="fw-bolder">{{p.marca.nombre}} {{p.nombre}}</h5>
                <!-- Product price-->
                <p class="card-text">${{p.precio}}</p>
                
            </div>
        </a>    
    </div>
    <!-- Product actions-->
    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
        <div class="text-center">
            <a href="{% url 'orden:update_item' type='add' pk=p.id %}">
                <button data-producto="{{p.id}}" data-action="add" class="btn btn-outline-dark mt-auto update-carrito">Agregar a carrito</button>
            </a>
        </div>
    </div>
</div>