src/apps/ordenes/urls.py
from django.urls import path
from . import views

app_name = "orden"


urlpatterns = [
    #path("ListarProductos/", views.listar, name="listar"),
    #path("update_item/", views.updateItem, name="update_item"),
    path("update_item/<str:type>/<int:pk>", views.updateItem, name="update_item"),
]

src/apps/productos/urls.py
from django.urls import path
from . import views
from apps.comentarios import views as views_c

app_name = "productos"

urladmin = [
    path("Admin/Listar/", views.ListarAdmin.as_view(), name="admin_listar"),
    path("Admin/Nuevo/", views.Crear.as_view(), name="admin_nuevo"),
    path("Admin/Editar/<int:pk>/", views.Editar.as_view(), name="admin_editar"),
    path("Admin/Borrar/<int:pk>/", views.borrar, name="admin_borrar"),
    path("Admin/Detalle/<int:pk>/", views.Detalle.as_view(), name="admin_detalle"),

]

urlsite = [
    #path("ListarProductos/", views.listar, name="listar"),
    path("Listar/", views.Listar.as_view(), name="listar"),
    path("Favoritos", views.ListarFavoritos.as_view(), name="listar_favoritos"),
    path("<int:pk>/", views.producto_detalle, name="detalle"),
    path("AgregarFavorito/<int:id>/", views.manejar_favorito, name="manejar_favorito"),
    #path("<int:id>/comentar", views_c.agregar, name="agregar_comentario")
]

urlpatterns = urladmin + urlsite

src/hugoOfemme/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    #Includes
    path("Productos/", include("apps.productos.urls")),
    path("Usuario/", include("apps.usuarios.urls")),
    path("", include("apps.ordenes.urls")),

    #Urls propias del proyecto
    #path("", views.inicio, name="inicio"),
    path("", views.Inicio.as_view(), name = "inicio"),
    path("login/", auth_views.LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", auth_views.logout_then_login, name="logout"),
    path("checkout/", views.checkout, name="checkout"),
    path("Carrito/", views.carrito, name="carrito"),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

src/templates/carrito/main.html
{% extends 'base/base.html' %}
{% load static %}
{% block contenido %}
	<div class="row">
		<div class="col-lg-12">
			<div class="container">
                <a  class="btn btn-outline-dark" href="{% url 'productos:listar' %}">&#x2190; Continuar comprando</a>

				<br>
				<br>
				<table class="table">
					<tr>
						<th><h5>Productos: <strong>{{orden.get_cant_items}}</strong></h5></th>
						<th><h5>Total:<strong> ${{orden.get_total_carrito}}</strong></h5></th>
						<th>
							<a  style="float:right; margin:5px;" class="btn btn-success" href="{% url 'checkout' %}">Comprar</a>
						</th>
					</tr>
				</table>
			</div>
			<br>
			<div class="container">
				<table class="table">
					<tr>
						<th></th>
						<th><h5>Producto</h5></th>
						<th><h5>Precio</h5></th>
						<th><h5>Cantidad</h5></th>
						<th><h5>Total</h5></th>
					</tr>
					{% for item in items %}
					<tr>
						<td><img class="row-image" height="100px" src="{{item.producto.imagen.url}}"></td>
						<td><p>{{item.producto.nombre}}</p></td>
						<td><p>{{item.producto.precio}}</p></td>
						<td>
							<div style="display:flex">
								{{item.cantidad}}
								<div class="quantity" style="display:flex; flex-direction:column; justify-content:space-between; margin-left: 5px">
									<a href="{% url 'orden:update_item' type='add' pk=item.producto.id %}">
										<img height="10px" class="update-carrito" data-producto="{{item.producto.id}}" data-action="add" src="https://stepswithcode.s3-us-west-2.amazonaws.com/m1-prt8/3+arrow-up.png">
									</a>
									<a href="{% url 'orden:update_item' type='remove' pk=item.producto.id %}">
										<img data-producto="{{item.producto.id}}" data-action="remove" height="10px" class="update-carrito" src="https://stepswithcode.s3-us-west-2.amazonaws.com/m1-prt8/2+arrow-down.png">
									</a>
								</div>
							</div>
						</td>
						<td><p>{{item.get_total}}</p></td>
					</tr>
					{% endfor %}
				</table>				
			</div>
		</div>
	</div>
{% endblock contenido %}